### ISSUE TITLE
[Frontend] Include a Custom Scroll Bar

### ISSUE THREAD

**Issue by ShriramG24** [UMass-Rescue/RescueBox-Desktop#137]
AC: Include a custom scroll bar to avoid layout shift when switching between Models page and Registration page (and any page for that matter).

**Comment by atharvakale343** [comment]
The scroll bar looks okay now. There is no longer a layout shift. @ShriramG24 @Shreneken let me know if there is a layout shift in Windows.

**Comment by ShriramG24** [comment]
Looks alright to me. We can close this for now.
