### ISSUE TITLE
[Backend] Integrate Small Block Forensics FlaskML Server

### ISSUE THREAD

**Issue by ShriramG24** [UMass-Rescue/RescueBox-Desktop#141]
AC: SBF service should provide API for running model, checking health, and sending model metadata. Write corresponding inference service and test to ensure calls are being made correctly.

**Comment by atharvakale343** [comment]
@ShriramG24 does this include also creating the model specific components on the frontend? Or is it just the backend integration?

**Comment by ShriramG24** [comment]
Just backend. I'll make separate issues for frontend components.
