### ISSUE TITLE
[Combined] Model Metadata and Info

### ISSUE THREAD

**Issue by atharvakale343** [UMass-Rescue/RescueBox-Desktop#214]
AC:

1. Make FlaskML changes to allow users to supply model info markdown strings, model name, author, last Updated etc.
2. Store markdown in RBox backend DB
3. Displaying info page markdown in frontend (when both model is online and offline)

**Comment by atharvakale343** [comment]
https://github.com/UMass-Rescue/Flask-ML/pull/34

**Comment by ShriramG24** [comment]
Marking as completed.

**Comment by atharvakale343** [comment]
This is completed
