### ISSUE TITLE
[Frontend] Reduce Jobs page to Single Table

### ISSUE THREAD

**Issue by atharvakale343** [UMass-Rescue/RescueBox-Desktop#217]
AC: Jobs page should have a single table arranged in descending order of start time where running jobs appear at its head. When a job completes, only that row should change in-place, preventing a large, disorienting layout shift.

**Comment by Shreneken** [comment]
Bug to fixed alongside this - Jobs page allows clicking inspect on a running job, resulting in an error, as mentioned in #221
