### ISSUE TITLE
[Frontend] Registration/Models Pages Updates

### ISSUE THREAD

**Issue by atharvakale343** [UMass-Rescue/RescueBox-Desktop#228]
Pre-requisite: https://github.com/UMass-Rescue/RescueBox-Desktop/issues/229

AC: In models page, add a column for version and a delete button. Add a column in model db table and task table called userDeleted. If the delete button is clicked, it should set the model row in models DB table and all associated tasks to userDeleted=true, and also completely delete a server row, if a server row exists for that modelUid. User deleted models should never be shown again. If a user registers a model that happens to match the same modelUid, then reverse all the changes above (set userDeleted to false in modelDB, tasksDB).

Similar delete button should be there in Registration page. Include both version and last updated as new columns in the UI table in registration page.

Share logic between both delete buttons

**Comment by Shreneken** [comment]
Closed by #330
