### ISSUE TITLE
Duplicate instances of the same Model are created when trying to reconnect to a server

### ISSUE THREAD

**Issue by prasannals** [UMass-Rescue/RescueBox-Desktop#328]
![image](https://github.com/user-attachments/assets/e15018af-5f05-4a03-bd84-7b551d23591f)

There needs to be some way to identify a model uniquely across multiple connections. Might involve changes in both the frontend and Flask-ML backend.

**Comment by Shreneken** [comment]
#330 you can now remove models if you registered multiple instances of the same model app. Ideally, you wouldn't want to register the same app multiple times and connect to it instead.

**Comment by prasannals** [comment]
@atharvakale343 @Shreneken Thanks for the update. This sounds good. I'll close the issue and try the recommended solutions. I might reopen it later if this needs further work.
